### PR TITLE
feat(svg_fmt): ability to add a comment to shapes

### PR DESCRIPTION
**Pull request by problame**
Neon's use case: https://github.com/neondatabase/neon/pull/7455

Happy to do adjustments or extend this to other structs if that is what's required to get this PR over the finish line.

### CODE REVIEW

**Comment by nical** [comment]
Hi, Thanks for this PR. Adding comments by putting stuff inside the rect element does not look quite like something the SVG spec itended, but I suppose if we run into issues later we can just move it into a real svg comment.

Please add this to the other shapes for consistency.

**Comment by problame** [comment]
Pushed the requested changes.

Note that the addition of the `Comment` field forces us to remove us the `derive(Copy)`, hence it's a breaking change to the API.

**Comment by problame** [comment]
It's been a week. Any timeline on when I can expect a review / merge? :) 

I'm also OK with a rejection; would just like to wrap this up soon.

**Comment by problame** [comment]
@nical , kindly asking for a decision 🙏

**Comment by nical** [comment]
Sorry for the delay, let's take this.

**Pull request merged**
